env:
  global:
  - secure: [IrTuZNvNrUD3Jy253ya25rh86N6OJ+05SGWlIWx4YOeWiymlxTsncPpwIC807oaec9gcdyiEH0DYnk/nlqkx91cSp0TQxgCGFov9WnfYLsXfcdAwbsMERv2gQcy2BmbgWE3gzMTGgZG2VbVZeSDWmbQxpsckw5LVKxhBqDF0SBg=]

language: node_js
sudo: false
node_js:
  - "4.0.0"
before_script:
  - npm install
  - npm -g install jspm
  - jspm install
script:
  - npm run test
