language: node_js
sudo: false
node_js:
- 4.0.0
before_script:
- npm install
- npm -g install jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
- jspm setmode remote
script:
- echo 'development' > config/.env && npm run test
env:
  global:
  - secure: G7cDSIFEiaOYvAfqgccxOkT/hgidL0uM7T9KAOriXNN0EG2xWIHb3tLSrG+v8Rf8RIBj7e0PcnLMi5N8f5rx1HIFn31BsCRHOZAaYM6X89XCixy+vtIzf/KFvZQWDHtUxotxZ+ms5uUiPfo+5ykgPNTJCAilYIiG0/oV27OPaqM=
