language: node_js
sudo: false
node_js:
- 4.0.0
before_install:
- npm -g install jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
before_script:
- jspm setmode remote
script:
- echo 'development' > config/.env && npm run test
