language: node_js
sudo: false
node_js:
- 4.0.0
before_script:
- npm install
- npm -g install jspm
- jspm install
- jspm setmode remote
script:
- echo 'development' > config/.env && npm run test
env:
  global:
  - secure: FVWJK77TYHoqRBoooccwMHGdzh8Uyikq6sXmFpuSYBhQkq5Y+ecnDS9GV3MiMmYHV3wnUkr06fQL7oMdoFSAnejjK4RreTmJ8FyQ0FZBas8rAD/U+8jWXt9qNj+KfKBsAR4iWn0gVmphxJgy6hRktpvbq9CsWSbmSwj2p8Eqe6A=
