language: node_js
sudo: false
node_js:
- 4.0.0
before_script:
- npm install
- npm -g install jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
- jspm setmode remote
script:
- echo 'development' > config/.env && npm run test
env:
  global:
  - secure: H4UZFsAovKgEJFOdjOBw42P6XZ1+TVPjrX9OprtRuQHCPOUP0mH2i86Gjyh2aiz0XOMNbUoxtr13BLrnhfY3C0qJ0bXQhqu3EbI2OKg82IC7POC2IB4CUXKjLS1NaUefx2vxUqau/oYsOVArJeOl9Bv2BNuMyL8hNucm3yAs9aE=
